### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by toufreach5** [yandex-cloud/cq-provider-yandex#15]
Hello,

Did you plan to create a new releases after this commit https://github.com/yandex-cloud/cq-provider-yandex/commit/5b43a45c3db4e604e737dde45ca81fd5f0d93605 ?

Thanks,
Best regards

**Comment by valyankilyan** [comment]
new release [v0.1.2](https://github.com/yandex-cloud/cq-provider-yandex/releases/tag/v0.1.2)
