### ISSUE TITLE
Question re case-study

### ISSUE THREAD

**Issue by yevgenypats** [yandex-cloud/cq-provider-yandex#8]
Hi Folks, (Sorry if it's not the right place but I wasn't able to find any email/relevant contact)

It's Yevgeny Pats, CEO of CloudQuery. I wanted to ask you, if we can get a quote from you or from another developer that worked on cq-provider-yandex for a blog/case-study we are working on, to help us grow our developers ecosystem? 

Again, don't know who I should contact for such requests, but will appreciate it if you can direct me to the right contact for such requests? If this is not something you can do - totally fine and thanks for building this great plugin!

Cheers,
Yevgeny

/cc @GennadySpb

**Comment by GennadySpb** [comment]
Hi @yevgenypats !
I recently sent you an email to clarify the details about your request.

**Comment by yevgenypats** [comment]
Thank you! Closing. Looking forward to collaborate more on this provider!
